version: "3.9"

services:

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile

    container_name: churn-fastapi

    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: docker/streamlit.Dockerfile

    container_name: churn-streamlit

    ports:
      - "8501:8501"

    depends_on:
      - fastapi



  mysql:
    image: mysql:8.0

    container_name: churn-mysql

    environment:
      MYSQL_ROOT_PASSWORD: Sudip@2003
      MYSQL_DATABASE: churn_db

    ports:
      - "3306:3306"

  